steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/Airdrop-Tracker', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
timeout: '1600s'
